version: "3.5"
services:
  rinha-api-01: # API - Instância 01
    image: rinhadebackend.api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: rinha-api-01
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  rinha-api-02: # API - Instância 02
    image: rinhadebackend.api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: rinha-api-02
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-api-01
      - rinha-api-02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  db: # Banco de dados
    image: postgres
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"

networks:
  default:
    driver: bridge
    name: rinha
