name: Publish Docker image

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: gustmrg/rinha-backend-api

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        with:
          context: src
          file: RinhaDeBackEnd.API/Dockerfile
        run: docker image build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} -t ${{ env.DOCKER_IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: docker image push --all-tags ${{ env.DOCKER_IMAGE_NAME }}